# Generated by Django 4.2.7 on 2024-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('dateTime', models.DateField(auto_now_add=True)),
                ('people', models.IntegerField()),
                ('specialRequest', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
