# Generated by Django 5.0.2 on 2024-03-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0005_rename_items_category_items_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='items_category',
            new_name='name',
        ),
    ]
