# Generated by Django 5.0.2 on 2024-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0006_rename_items_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='table_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
