# Generated by Django 5.0.2 on 2024-03-05 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0007_booktable_table_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='No_People',
            new_name='no_people',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Ph_Number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='SpecialRequest',
        ),
        migrations.AddField(
            model_name='booktable',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booktable',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
