# Generated by Django 5.0.2 on 2024-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0008_rename_email_booktable_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
