# Generated by Django 5.0.2 on 2024-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0009_alter_booktable_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='no_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
