# Generated by Django 5.0.2 on 2024-03-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0010_alter_booktable_no_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('table_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restro_App.booktable')),
            ],
        ),
    ]
