# Generated by Django 5.0.2 on 2024-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0011_tableprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='no_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='table_no',
            field=models.IntegerField(),
        ),
    ]
