# Generated by Django 5.0.2 on 2024-03-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restro_App', '0012_alter_booktable_email_alter_booktable_no_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(max_length=5)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tableprice',
            name='table_no',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('people', models.IntegerField()),
                ('number', models.CharField(max_length=14)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restro_App.table')),
            ],
        ),
        migrations.DeleteModel(
            name='BookTable',
        ),
        migrations.DeleteModel(
            name='TablePrice',
        ),
    ]
